defaults:
  - augment: baseline

data:
  name: cifar10
  val_size: 5_000
  batch_size: 128
  download: false

optim:
  model:
    lr: 1e-1
    weight_decay: 5e-4

  epochs:
    200

model:
  name: wrn28_2

verb: false
debug: false
seed: 1
gpu_id: 0
